// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lightning} from '../models';
import {db} from '../models';
import {config} from '../models';
import {orchestration} from '../models';
import {acp} from '../models';

export function AddComment(arg1:string,arg2:string):Promise<string>;

export function AddExternalProject(arg1:string,arg2:string,arg3:boolean):Promise<Record<string, any>>;

export function AddGoldSample(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddIdentity(arg1:string,arg2:string):Promise<void>;

export function AddMCPServer(arg1:string,arg2:string):Promise<string>;

export function AnalyzeGraphHealth():Promise<Record<string, any>>;

export function ApproveAction(arg1:string,arg2:string):Promise<string>;

export function ApprovePromptVariant(arg1:string):Promise<string>;

export function AskAgent(arg1:string,arg2:string):Promise<string>;

export function BindLightning(arg1:lightning.DuckDBStore):Promise<void>;

export function CheckConnection():Promise<boolean>;

export function ClearWorkspace():Promise<Record<string, string>>;

export function ConsolidateChatKnowledge(arg1:string,arg2:string):Promise<string>;

export function CreateAgent(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function CreateGoal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function DetectLMStudioEmbeddingDimension(arg1:string):Promise<number>;

export function ExecuteFullSync():Promise<string>;

export function ExportRLHFDataset():Promise<string>;

export function ExportTelemetry():Promise<string>;

export function FixEnvironment():Promise<string>;

export function FullSync():Promise<string>;

export function GenerateGeminiMD():Promise<string>;

export function GetAgentSecrets(arg1:string):Promise<Array<db.AgentSecret>>;

export function GetAgents():Promise<Array<db.Agent>>;

export function GetAutonomousMode():Promise<boolean>;

export function GetConfig():Promise<config.Config>;

export function GetDocuments(arg1:string):Promise<Array<db.Document>>;

export function GetExecutiveSummary():Promise<orchestration.ExecSummary>;

export function GetExternalProjects():Promise<Array<config.ProjectScan>>;

export function GetGoals():Promise<Array<db.Goal>>;

export function GetIssueTimeline(arg1:string):Promise<Array<db.IssueComment>>;

export function GetIssues():Promise<Array<db.Issue>>;

export function GetLatestSpans():Promise<Array<Record<string, any>>>;

export function GetLightningStats():Promise<Record<string, any>>;

export function GetNeuralNodeContext(arg1:string):Promise<Record<string, any>>;

export function GetPendingApprovals():Promise<Array<db.Approval>>;

export function GetPlanMode(arg1:string):Promise<boolean>;

export function GetProjectDoc(arg1:string):Promise<string>;

export function GetPromptCandidates():Promise<Array<Record<string, any>>>;

export function GetPromptHistory(arg1:string):Promise<Array<Record<string, any>>>;

export function GetSkeletalGraph():Promise<Record<string, any>>;

export function GetToolsStatus():Promise<Record<string, boolean>>;

export function GetWorkspace():Promise<Record<string, string>>;

export function HandleNodeClick(arg1:string):Promise<void>;

export function InstallTool(arg1:string):Promise<string>;

export function IsExplorationMode():Promise<boolean>;

export function ListAgentSessions(arg1:string):Promise<Array<acp.SessionInfo>>;

export function ListLMStudioModels():Promise<Array<string>>;

export function ListMCPServers():Promise<string>;

export function LoadAgentSession(arg1:string,arg2:string):Promise<void>;

export function LoadFastGraph():Promise<void>;

export function LogNeuralActivity(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function LoginIdentity(arg1:string,arg2:string):Promise<void>;

export function NewAgentSession(arg1:string):Promise<void>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function PruneGraph(arg1:number):Promise<string>;

export function PurgeCache():Promise<string>;

export function ReadGeminiConfig():Promise<string>;

export function RejectAction(arg1:string,arg2:string):Promise<string>;

export function RemoveIdentity(arg1:string,arg2:string):Promise<void>;

export function ResetQdrantDB():Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<string>;

export function RunInTerminal(arg1:string):Promise<string>;

export function RunReconScan():Promise<string>;

export function RunVectorDiagnostic():Promise<Record<string, any>>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanVault():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectWorkspace():Promise<Record<string, string>>;

export function SendAgentInput(arg1:string,arg2:string,arg3:Array<Record<string, string>>):Promise<void>;

export function SendMessageToSwarm(arg1:string,arg2:string):Promise<string>;

export function SendSteeringHint(arg1:string,arg2:string):Promise<string>;

export function SendTerminalData(arg1:string,arg2:string):Promise<void>;

export function SetAgentModel(arg1:string,arg2:string):Promise<void>;

export function SetAutonomousMode(arg1:boolean):Promise<string>;

export function SetExplorationMode(arg1:boolean):Promise<string>;

export function SetPlanMode(arg1:string,arg2:boolean):Promise<boolean>;

export function SetWorkspace(arg1:string):Promise<void>;

export function SetupTool(arg1:string):Promise<string>;

export function StartAgentSession(arg1:string):Promise<void>;

export function StartBackgroundAgentSession(arg1:string):Promise<void>;

export function StartLoginSession(arg1:string):Promise<string>;

export function StopAgentSession(arg1:string):Promise<void>;

export function SubmitReview(arg1:string,arg2:boolean):Promise<void>;

export function SwitchIdentity(arg1:string,arg2:string):Promise<void>;

export function SyncAllNodes():Promise<void>;

export function TestLMStudioModel(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ToggleProjectCodeRAG(arg1:string):Promise<Record<string, any>>;

export function TriggerInitialSync():Promise<string>;

export function TriggerReflection(arg1:string):Promise<string>;

export function TriggerZoom(arg1:string):Promise<void>;

export function UnlinkProject(arg1:string):Promise<void>;

export function UpdateAgentSecret(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateNodePositions(arg1:Array<Record<string, any>>):Promise<string>;

export function UpsertDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function WeaveNeuralLinks(arg1:number):Promise<void>;

export function WriteGeminiConfig(arg1:string):Promise<void>;
