// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComment(arg1, arg2) {
  return window['go']['core']['App']['AddComment'](arg1, arg2);
}

export function AddExternalProject(arg1, arg2, arg3) {
  return window['go']['core']['App']['AddExternalProject'](arg1, arg2, arg3);
}

export function AddGeminiAccount(arg1) {
  return window['go']['core']['App']['AddGeminiAccount'](arg1);
}

export function AddGoldSample(arg1, arg2, arg3) {
  return window['go']['core']['App']['AddGoldSample'](arg1, arg2, arg3);
}

export function AddMCPServer(arg1, arg2) {
  return window['go']['core']['App']['AddMCPServer'](arg1, arg2);
}

export function AnalyzeGraphHealth() {
  return window['go']['core']['App']['AnalyzeGraphHealth']();
}

export function ApproveAction(arg1, arg2) {
  return window['go']['core']['App']['ApproveAction'](arg1, arg2);
}

export function ApprovePromptVariant(arg1) {
  return window['go']['core']['App']['ApprovePromptVariant'](arg1);
}

export function AskAgent(arg1, arg2) {
  return window['go']['core']['App']['AskAgent'](arg1, arg2);
}

export function BindLightning(arg1) {
  return window['go']['core']['App']['BindLightning'](arg1);
}

export function CheckConnection() {
  return window['go']['core']['App']['CheckConnection']();
}

export function ConsolidateChatKnowledge(arg1, arg2) {
  return window['go']['core']['App']['ConsolidateChatKnowledge'](arg1, arg2);
}

export function CreateAgent(arg1, arg2, arg3, arg4) {
  return window['go']['core']['App']['CreateAgent'](arg1, arg2, arg3, arg4);
}

export function CreateGoal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['core']['App']['CreateGoal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['core']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteSession(arg1) {
  return window['go']['core']['App']['DeleteSession'](arg1);
}

export function DetectLMStudioEmbeddingDimension(arg1) {
  return window['go']['core']['App']['DetectLMStudioEmbeddingDimension'](arg1);
}

export function ExportRLHFDataset() {
  return window['go']['core']['App']['ExportRLHFDataset']();
}

export function ExportTelemetry() {
  return window['go']['core']['App']['ExportTelemetry']();
}

export function FixEnvironment() {
  return window['go']['core']['App']['FixEnvironment']();
}

export function FullSync() {
  return window['go']['core']['App']['FullSync']();
}

export function GenerateGeminiMD() {
  return window['go']['core']['App']['GenerateGeminiMD']();
}

export function GetAgentSecrets(arg1) {
  return window['go']['core']['App']['GetAgentSecrets'](arg1);
}

export function GetAgents() {
  return window['go']['core']['App']['GetAgents']();
}

export function GetAutonomousMode() {
  return window['go']['core']['App']['GetAutonomousMode']();
}

export function GetConfig() {
  return window['go']['core']['App']['GetConfig']();
}

export function GetDocuments(arg1) {
  return window['go']['core']['App']['GetDocuments'](arg1);
}

export function GetExecutiveSummary() {
  return window['go']['core']['App']['GetExecutiveSummary']();
}

export function GetExternalProjects() {
  return window['go']['core']['App']['GetExternalProjects']();
}

export function GetGoals() {
  return window['go']['core']['App']['GetGoals']();
}

export function GetIssueTimeline(arg1) {
  return window['go']['core']['App']['GetIssueTimeline'](arg1);
}

export function GetIssues() {
  return window['go']['core']['App']['GetIssues']();
}

export function GetLatestSpans() {
  return window['go']['core']['App']['GetLatestSpans']();
}

export function GetLightningStats() {
  return window['go']['core']['App']['GetLightningStats']();
}

export function GetNodeDetails(arg1) {
  return window['go']['core']['App']['GetNodeDetails'](arg1);
}

export function GetPendingApprovals() {
  return window['go']['core']['App']['GetPendingApprovals']();
}

export function GetProjectDoc(arg1) {
  return window['go']['core']['App']['GetProjectDoc'](arg1);
}

export function GetPromptCandidates() {
  return window['go']['core']['App']['GetPromptCandidates']();
}

export function GetPromptHistory(arg1) {
  return window['go']['core']['App']['GetPromptHistory'](arg1);
}

export function GetSkeletalGraph() {
  return window['go']['core']['App']['GetSkeletalGraph']();
}

export function GetToolsStatus() {
  return window['go']['core']['App']['GetToolsStatus']();
}

export function HandleNodeClick(arg1) {
  return window['go']['core']['App']['HandleNodeClick'](arg1);
}

export function InstallTool(arg1) {
  return window['go']['core']['App']['InstallTool'](arg1);
}

export function IsExplorationMode() {
  return window['go']['core']['App']['IsExplorationMode']();
}

export function ListAgentSessions(arg1) {
  return window['go']['core']['App']['ListAgentSessions'](arg1);
}

export function ListLMStudioModels() {
  return window['go']['core']['App']['ListLMStudioModels']();
}

export function ListMCPServers() {
  return window['go']['core']['App']['ListMCPServers']();
}

export function LoadAgentSession(arg1, arg2) {
  return window['go']['core']['App']['LoadAgentSession'](arg1, arg2);
}

export function LoginGeminiAccount(arg1) {
  return window['go']['core']['App']['LoginGeminiAccount'](arg1);
}

export function NewAgentSession(arg1) {
  return window['go']['core']['App']['NewAgentSession'](arg1);
}

export function OpenFileInEditor(arg1) {
  return window['go']['core']['App']['OpenFileInEditor'](arg1);
}

export function PruneGraph(arg1) {
  return window['go']['core']['App']['PruneGraph'](arg1);
}

export function PurgeCache() {
  return window['go']['core']['App']['PurgeCache']();
}

export function RejectAction(arg1, arg2) {
  return window['go']['core']['App']['RejectAction'](arg1, arg2);
}

export function ResetQdrantDB() {
  return window['go']['core']['App']['ResetQdrantDB']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['core']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['core']['App']['ResolveConflict'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunInTerminal(arg1) {
  return window['go']['core']['App']['RunInTerminal'](arg1);
}

export function RunReconScan() {
  return window['go']['core']['App']['RunReconScan']();
}

export function RunVectorDiagnostic() {
  return window['go']['core']['App']['RunVectorDiagnostic']();
}

export function SaveConfig(arg1) {
  return window['go']['core']['App']['SaveConfig'](arg1);
}

export function ScanVault() {
  return window['go']['core']['App']['ScanVault']();
}

export function SelectDirectory() {
  return window['go']['core']['App']['SelectDirectory']();
}

export function SendAgentInput(arg1, arg2, arg3) {
  return window['go']['core']['App']['SendAgentInput'](arg1, arg2, arg3);
}

export function SendMessageToSwarm(arg1, arg2) {
  return window['go']['core']['App']['SendMessageToSwarm'](arg1, arg2);
}

export function SendTerminalData(arg1, arg2) {
  return window['go']['core']['App']['SendTerminalData'](arg1, arg2);
}

export function SetAutonomousMode(arg1) {
  return window['go']['core']['App']['SetAutonomousMode'](arg1);
}

export function SetExplorationMode(arg1) {
  return window['go']['core']['App']['SetExplorationMode'](arg1);
}

export function SetupTool(arg1) {
  return window['go']['core']['App']['SetupTool'](arg1);
}

export function StartAgentSession(arg1) {
  return window['go']['core']['App']['StartAgentSession'](arg1);
}

export function StartBackgroundAgentSession(arg1) {
  return window['go']['core']['App']['StartBackgroundAgentSession'](arg1);
}

export function StartLoginSession(arg1) {
  return window['go']['core']['App']['StartLoginSession'](arg1);
}

export function StopAgentSession(arg1) {
  return window['go']['core']['App']['StopAgentSession'](arg1);
}

export function SubmitReview(arg1, arg2) {
  return window['go']['core']['App']['SubmitReview'](arg1, arg2);
}

export function SwitchGeminiAccount(arg1) {
  return window['go']['core']['App']['SwitchGeminiAccount'](arg1);
}

export function SyncAllNodes() {
  return window['go']['core']['App']['SyncAllNodes']();
}

export function TestLMStudioModel(arg1, arg2) {
  return window['go']['core']['App']['TestLMStudioModel'](arg1, arg2);
}

export function TriggerReflection(arg1) {
  return window['go']['core']['App']['TriggerReflection'](arg1);
}

export function UpdateAgentSecret(arg1, arg2, arg3) {
  return window['go']['core']['App']['UpdateAgentSecret'](arg1, arg2, arg3);
}

export function UpsertDocument(arg1, arg2, arg3, arg4) {
  return window['go']['core']['App']['UpsertDocument'](arg1, arg2, arg3, arg4);
}

export function WeaveNeuralLinks(arg1) {
  return window['go']['core']['App']['WeaveNeuralLinks'](arg1);
}
