// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAgent(arg1) {
  return window['go']['main']['App']['AskAgent'](arg1);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function FixEnvironment() {
  return window['go']['main']['App']['FixEnvironment']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetToolsStatus() {
  return window['go']['main']['App']['GetToolsStatus']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanVault() {
  return window['go']['main']['App']['ScanVault']();
}

export function SendAgentInput(arg1, arg2) {
  return window['go']['main']['App']['SendAgentInput'](arg1, arg2);
}

export function SendTerminalData(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalData'](arg1, arg2);
}

export function SetupTool(arg1) {
  return window['go']['main']['App']['SetupTool'](arg1);
}

export function StartAgentSession(arg1) {
  return window['go']['main']['App']['StartAgentSession'](arg1);
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}
