// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGeminiAccount(arg1) {
  return window['go']['main']['App']['AddGeminiAccount'](arg1);
}

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AnalyzeGraphHealth() {
  return window['go']['main']['App']['AnalyzeGraphHealth']();
}

export function AskAgent(arg1, arg2) {
  return window['go']['main']['App']['AskAgent'](arg1, arg2);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function ConsolidateChatKnowledge(arg1, arg2) {
  return window['go']['main']['App']['ConsolidateChatKnowledge'](arg1, arg2);
}

export function FixEnvironment() {
  return window['go']['main']['App']['FixEnvironment']();
}

export function FullSync() {
  return window['go']['main']['App']['FullSync']();
}

export function GenerateGeminiMD() {
  return window['go']['main']['App']['GenerateGeminiMD']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetNodeDetails(arg1) {
  return window['go']['main']['App']['GetNodeDetails'](arg1);
}

export function GetProjectDoc(arg1) {
  return window['go']['main']['App']['GetProjectDoc'](arg1);
}

export function GetToolsStatus() {
  return window['go']['main']['App']['GetToolsStatus']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function ListAgentSessions(arg1) {
  return window['go']['main']['App']['ListAgentSessions'](arg1);
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function LoadAgentSession(arg1, arg2) {
  return window['go']['main']['App']['LoadAgentSession'](arg1, arg2);
}

export function LoginGeminiAccount(arg1) {
  return window['go']['main']['App']['LoginGeminiAccount'](arg1);
}

export function NewAgentSession(arg1) {
  return window['go']['main']['App']['NewAgentSession'](arg1);
}

export function OpenFileInEditor(arg1) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1);
}

export function PurgeCache() {
  return window['go']['main']['App']['PurgeCache']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunVectorDiagnostic() {
  return window['go']['main']['App']['RunVectorDiagnostic']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanVault() {
  return window['go']['main']['App']['ScanVault']();
}

export function SendAgentInput(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendAgentInput'](arg1, arg2, arg3);
}

export function SendTerminalData(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalData'](arg1, arg2);
}

export function SetAutonomousMode(arg1) {
  return window['go']['main']['App']['SetAutonomousMode'](arg1);
}

export function SetupTool(arg1) {
  return window['go']['main']['App']['SetupTool'](arg1);
}

export function StartAgentSession(arg1) {
  return window['go']['main']['App']['StartAgentSession'](arg1);
}

export function StartLoginSession(arg1) {
  return window['go']['main']['App']['StartLoginSession'](arg1);
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}

export function SubmitReview(arg1, arg2) {
  return window['go']['main']['App']['SubmitReview'](arg1, arg2);
}

export function SwitchGeminiAccount(arg1) {
  return window['go']['main']['App']['SwitchGeminiAccount'](arg1);
}
