// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {config} from '../models';
import {orchestration} from '../models';
import {agents} from '../models';

export function AddComment(arg1:string,arg2:string):Promise<string>;

export function AddGeminiAccount(arg1:string):Promise<void>;

export function AddMCPServer(arg1:string,arg2:string):Promise<string>;

export function AnalyzeGraphHealth():Promise<Record<string, any>>;

export function ApproveAction(arg1:string,arg2:string):Promise<string>;

export function AskAgent(arg1:string,arg2:string):Promise<string>;

export function CheckConnection():Promise<boolean>;

export function ConsolidateChatKnowledge(arg1:string,arg2:string):Promise<string>;

export function CreateAgent(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function CreateGoal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FixEnvironment():Promise<string>;

export function FullSync():Promise<string>;

export function GenerateGeminiMD():Promise<string>;

export function GetAgentSecrets(arg1:string):Promise<Array<db.AgentSecret>>;

export function GetAgents():Promise<Array<db.Agent>>;

export function GetConfig():Promise<config.Config>;

export function GetDocuments(arg1:string):Promise<Array<db.Document>>;

export function GetExecutiveSummary():Promise<orchestration.ExecSummary>;

export function GetGoals():Promise<Array<db.Goal>>;

export function GetIssueTimeline(arg1:string):Promise<Array<db.IssueComment>>;

export function GetIssues():Promise<Array<db.Issue>>;

export function GetNodeDetails(arg1:string):Promise<Record<string, any>>;

export function GetPendingApprovals():Promise<Array<db.Approval>>;

export function GetProjectDoc(arg1:string):Promise<string>;

export function GetToolsStatus():Promise<Record<string, boolean>>;

export function HandleNodeClick(arg1:string):Promise<void>;

export function InstallTool(arg1:string):Promise<string>;

export function IsExplorationMode():Promise<boolean>;

export function ListAgentSessions(arg1:string):Promise<Array<agents.SessionInfo>>;

export function ListMCPServers():Promise<string>;

export function LoadAgentSession(arg1:string,arg2:string):Promise<void>;

export function LoginGeminiAccount(arg1:string):Promise<void>;

export function NewAgentSession(arg1:string):Promise<void>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function PurgeCache():Promise<string>;

export function RejectAction(arg1:string,arg2:string):Promise<string>;

export function ResetQdrantDB():Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<string>;

export function RunVectorDiagnostic():Promise<Record<string, any>>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanVault():Promise<string>;

export function SendAgentInput(arg1:string,arg2:string,arg3:Array<Record<string, string>>):Promise<void>;

export function SendTerminalData(arg1:string,arg2:string):Promise<void>;

export function SetAutonomousMode(arg1:boolean):Promise<string>;

export function SetExplorationMode(arg1:boolean):Promise<string>;

export function SetupTool(arg1:string):Promise<string>;

export function StartAgentSession(arg1:string):Promise<void>;

export function StartLoginSession(arg1:string):Promise<string>;

export function StopAgentSession(arg1:string):Promise<void>;

export function SubmitReview(arg1:string,arg2:boolean):Promise<void>;

export function SwitchGeminiAccount(arg1:string):Promise<void>;

export function SyncAllNodes():Promise<void>;

export function UpdateAgentSecret(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpsertDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function WeaveNeuralLinks(arg1:number):Promise<void>;
