// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComment(arg1, arg2) {
  return window['go']['main']['App']['AddComment'](arg1, arg2);
}

export function AddGeminiAccount(arg1) {
  return window['go']['main']['App']['AddGeminiAccount'](arg1);
}

export function AddGoldSample(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddGoldSample'](arg1, arg2, arg3);
}

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AnalyzeGraphHealth() {
  return window['go']['main']['App']['AnalyzeGraphHealth']();
}

export function ApproveAction(arg1, arg2) {
  return window['go']['main']['App']['ApproveAction'](arg1, arg2);
}

export function ApprovePromptVariant(arg1) {
  return window['go']['main']['App']['ApprovePromptVariant'](arg1);
}

export function AskAgent(arg1, arg2) {
  return window['go']['main']['App']['AskAgent'](arg1, arg2);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function ConsolidateChatKnowledge(arg1, arg2) {
  return window['go']['main']['App']['ConsolidateChatKnowledge'](arg1, arg2);
}

export function CreateAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2, arg3, arg4);
}

export function CreateGoal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateGoal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function ExportRLHFDataset() {
  return window['go']['main']['App']['ExportRLHFDataset']();
}

export function ExportTelemetry() {
  return window['go']['main']['App']['ExportTelemetry']();
}

export function FixEnvironment() {
  return window['go']['main']['App']['FixEnvironment']();
}

export function FullSync() {
  return window['go']['main']['App']['FullSync']();
}

export function GenerateGeminiMD() {
  return window['go']['main']['App']['GenerateGeminiMD']();
}

export function GetAgentSecrets(arg1) {
  return window['go']['main']['App']['GetAgentSecrets'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDocuments(arg1) {
  return window['go']['main']['App']['GetDocuments'](arg1);
}

export function GetExecutiveSummary() {
  return window['go']['main']['App']['GetExecutiveSummary']();
}

export function GetGoals() {
  return window['go']['main']['App']['GetGoals']();
}

export function GetIssueTimeline(arg1) {
  return window['go']['main']['App']['GetIssueTimeline'](arg1);
}

export function GetIssues() {
  return window['go']['main']['App']['GetIssues']();
}

export function GetLatestSpans() {
  return window['go']['main']['App']['GetLatestSpans']();
}

export function GetLightningStats() {
  return window['go']['main']['App']['GetLightningStats']();
}

export function GetNodeDetails(arg1) {
  return window['go']['main']['App']['GetNodeDetails'](arg1);
}

export function GetPendingApprovals() {
  return window['go']['main']['App']['GetPendingApprovals']();
}

export function GetProjectDoc(arg1) {
  return window['go']['main']['App']['GetProjectDoc'](arg1);
}

export function GetPromptCandidates() {
  return window['go']['main']['App']['GetPromptCandidates']();
}

export function GetPromptHistory(arg1) {
  return window['go']['main']['App']['GetPromptHistory'](arg1);
}

export function GetSkeletalGraph() {
  return window['go']['main']['App']['GetSkeletalGraph']();
}

export function GetToolsStatus() {
  return window['go']['main']['App']['GetToolsStatus']();
}

export function HandleNodeClick(arg1) {
  return window['go']['main']['App']['HandleNodeClick'](arg1);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function IsExplorationMode() {
  return window['go']['main']['App']['IsExplorationMode']();
}

export function ListAgentSessions(arg1) {
  return window['go']['main']['App']['ListAgentSessions'](arg1);
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function LoadAgentSession(arg1, arg2) {
  return window['go']['main']['App']['LoadAgentSession'](arg1, arg2);
}

export function LoginGeminiAccount(arg1) {
  return window['go']['main']['App']['LoginGeminiAccount'](arg1);
}

export function NewAgentSession(arg1) {
  return window['go']['main']['App']['NewAgentSession'](arg1);
}

export function OpenFileInEditor(arg1) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1);
}

export function PruneGraph(arg1) {
  return window['go']['main']['App']['PruneGraph'](arg1);
}

export function PurgeCache() {
  return window['go']['main']['App']['PurgeCache']();
}

export function RejectAction(arg1, arg2) {
  return window['go']['main']['App']['RejectAction'](arg1, arg2);
}

export function ResetQdrantDB() {
  return window['go']['main']['App']['ResetQdrantDB']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunReconScan() {
  return window['go']['main']['App']['RunReconScan']();
}

export function RunVectorDiagnostic() {
  return window['go']['main']['App']['RunVectorDiagnostic']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanVault() {
  return window['go']['main']['App']['ScanVault']();
}

export function SendAgentInput(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendAgentInput'](arg1, arg2, arg3);
}

export function SendMessageToSwarm(arg1, arg2) {
  return window['go']['main']['App']['SendMessageToSwarm'](arg1, arg2);
}

export function SendTerminalData(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalData'](arg1, arg2);
}

export function SetAutonomousMode(arg1) {
  return window['go']['main']['App']['SetAutonomousMode'](arg1);
}

export function SetExplorationMode(arg1) {
  return window['go']['main']['App']['SetExplorationMode'](arg1);
}

export function SetupTool(arg1) {
  return window['go']['main']['App']['SetupTool'](arg1);
}

export function StartAgentSession(arg1) {
  return window['go']['main']['App']['StartAgentSession'](arg1);
}

export function StartLoginSession(arg1) {
  return window['go']['main']['App']['StartLoginSession'](arg1);
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}

export function SubmitReview(arg1, arg2) {
  return window['go']['main']['App']['SubmitReview'](arg1, arg2);
}

export function SwitchGeminiAccount(arg1) {
  return window['go']['main']['App']['SwitchGeminiAccount'](arg1);
}

export function SyncAllNodes() {
  return window['go']['main']['App']['SyncAllNodes']();
}

export function TriggerReflection(arg1) {
  return window['go']['main']['App']['TriggerReflection'](arg1);
}

export function UpdateAgentSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAgentSecret'](arg1, arg2, arg3);
}

export function UpsertDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpsertDocument'](arg1, arg2, arg3, arg4);
}

export function WeaveNeuralLinks(arg1) {
  return window['go']['main']['App']['WeaveNeuralLinks'](arg1);
}
